# Generated by Django 4.2.4 on 2023-08-13 16:39

from django.db import migrations, models
import django.db.models.deletion
import onlinecourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_question_lesson_question_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default=onlinecourse.models.Lesson, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
        ),
    ]
